"""estrutura inicial

Revision ID: a3346e1bceec
Revises: 
Create Date: 2026-08-17 16:24:54.623482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3346e1bceec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agentes_faciais_agente_id_fkey'), 'agentes_faciais', type_='foreignkey')
    op.create_foreign_key(None, 'agentes_faciais', 'agentes', ['agente_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('embeddings_faciais_foto_id_fkey'), 'embeddings_faciais', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings_faciais', 'fotos', ['foto_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fotos_agente_id_fkey'), 'fotos', type_='foreignkey')
    op.drop_constraint(op.f('fotos_pessoa_id_fkey'), 'fotos', type_='foreignkey')
    op.create_foreign_key(None, 'fotos', 'pessoas', ['pessoa_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fotos', 'agentes', ['agente_id'], ['id'], ondelete='CASCADE')
    op.create_check_constraint('ck_foto_um_unico_dono', 'fotos', '\n            (pessoa_id IS NOT NULL AND agente_id IS NULL)\n            OR\n            (pessoa_id IS NULL AND agente_id IS NOT NULL)\n            ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_foto_um_unico_dono', 'fotos', type_='check')
    op.drop_constraint(None, 'fotos', type_='foreignkey')
    op.drop_constraint(None, 'fotos', type_='foreignkey')
    op.create_foreign_key(op.f('fotos_pessoa_id_fkey'), 'fotos', 'pessoas', ['pessoa_id'], ['id'])
    op.create_foreign_key(op.f('fotos_agente_id_fkey'), 'fotos', 'agentes', ['agente_id'], ['id'])
    op.drop_constraint(None, 'embeddings_faciais', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_faciais_foto_id_fkey'), 'embeddings_faciais', 'fotos', ['foto_id'], ['id'])
    op.drop_constraint(None, 'agentes_faciais', type_='foreignkey')
    op.create_foreign_key(op.f('agentes_faciais_agente_id_fkey'), 'agentes_faciais', 'agentes', ['agente_id'], ['id'])
    # ### end Alembic commands ###
